language: php

php:
- 5.5

install:
  - npm install -g eslint

script:
  - eslint .

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
